### ISSUE TITLE
Performance testing upper bounds

### ISSUE THREAD

**Issue by kworm83** [nchaigne/dhcperfcli#1]
Hi, thanks for a great tool.  I was wondering what you had been able to get to performance wise in total rate/s.  With DORA I have been unable to get beyond 30,000 all req/s or 15,000 DORA/s.  In looking at the CPU on the system running dhcperfcli it is pegged at 100% on a single core.  I'm guessing that it's not multi-threaded but was curious if you had any pointers to get beyond that performance level other than the obvious faster processor.

**Comment by nchaigne** [comment]
Hello,

Thanks for the feedback!

Yes it is single-threaded. The application limiting factor is the CPU, as you've noticed.
To benefit from multiple CPU you can launch several dhcperfcli instances concurrently (a simple shell script can do the job). To do so, you will need several source IP addresses on your test machine. Then each dhcpercli will act as a different gateway to the DHCP server.

You should probably ensure you're using different MAC address ranges so that the DHCP server is not confused.

For example, using 10.11.12.1 and 10.11.12.2 as gateways:

`echo "DHCP-Client-Hardware-Address=\"%{ethaddr.range:50:00:00:00:00:00-50:ff:ff:ff:ff:ff}\"" | dhcperfcli -T -L 60 -p 32 -g 10.11.12.1 10.11.12.42 dora &`

`echo "DHCP-Client-Hardware-Address=\"%{ethaddr.range:51:00:00:00:00:00-51:ff:ff:ff:ff:ff}\"" | dhcperfcli -T -L 60 -p 32 -g 10.11.12.2 10.11.12.42 dora &`


On Linux you can easily add secondary IP addresses to a given interface. For example (make sure nobody else has the address assigned already):

`ip addr add 10.11.12.2/27 dev eth1`

Or to make it permanent, create a new network configuration file (example is for RHEL / CentOS, adapt if you're using another distros):

`vim /etc/sysconfig/network-scripts/ifcfg-eth1:1`

With:

```TYPE=Ethernet
BOOTPROTO=none
DEVICE=eth1:1
ONBOOT=yes
IPADDR=10.11.12.2
NETMASK=255.255.255.224
NOZEROCONF=yes
```

**Comment by nchaigne** [comment]
That said, dhcperfcli may not be the limiting factor, even though you see the process using 100% of one CPU. It always does. This is because everything (sending, receiving, statistics...) is handled in an active loop. So your DHCP server may not be able to serve more than 15k DORA/s.

If you're not sure, try launching two dhcperfcli instances concurrently. If the sum of their DORA rate/s is still about 15k, it means the DHCP server is maxed out.

**Comment by kworm83** [comment]
Thanks for the quick response.  You are correct the sum remains at 15k DORA/s so the bottleneck is in fact the server performance...work to be done there for sure.
